import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { env } from 'process';

// This function gets called at build time
export async function getStaticProps() {
  const res = await fetch(`${env.URL_API}/api/whopays`)
  const pay = await res.json()

  return {
    props: {
      pay,
    },
  }
}

function Home( {pay} ) {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Quem paga esse mês?</p>
      <p>Qual mês: {pay.month}</p>
      <p>Pessoa: {pay.member.name}</p>
      <p>Data Vencimento: {pay.dueDate}</p>
      
    </section>
  )
}

export default Home