import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import useSWR from 'swr';

export default function Home() {
  const fetcher = (url) => fetch(url).then((res) => res.json())
  const { data } = useSWR('/api/data', fetcher)

  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Teste</p>
      <div>
        { 
          if(data !== 'undefined'){
            data.map( item => {
            console.log(item)
            if(item !== 'undefined'){
              return `<p> ${item} </p>`
            }
            }) 
          }
        }
      </div>
    </section>
  )
}